# netlify.toml (create in project root)
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"